url: https://conquermedieval.github.io
title: Nilsonlinux
description: Em desenvolvimento
keywords: Nilsonlinux, jekyll, jekyll-theme-blog
image: /assets/img/social.png
email: nilsonlinux@gmail.com
timezone: America/Sao_Paulo
branch: master
lang: pt_BR
author:
  name: Nilsonlinux
  email: nilsonlinux@gmail.com
twitter:
  site: null
  creator: nilsonlinux
google:
  site-verification: 7YAsvH47ykUFB4n7rYiqT6A9mi0WF5y_DjzRtUco4IY
  analytics: UA-75463090-6
  cse-cx: 007355044916868045354:qugwckco01q
  api-key: AIzaSyCRUkaEkWskwsaxUUZWHHkZXm8zXV15F6Q
disqus_shortname: jekyll-theme-docs
defaults:
  -
    scope:
      type: posts
    values:
      layout: post
      permalink: /:categories/:title
